# -*- coding: utf-8 -*-
"""Copy of Deep Learning with PyTorch : Siamese Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uZ1NQxFVNTZ9vHEXbWw9foSkHpIUaPt
"""

!pip install segmentation-models-pytorch
!pip install -U git+https://github.com/albumentations-team/albumentations
!pip install --upgrade opencv-contrib-python

"""# Download Full Dataset

Market-1501 dataset :
https://www.kaggle.com/pengcw1/market-1501
"""

!git clone https://github.com/parth1620/Person-Re-Id-Dataset


# Imports
"""

import sys
sys.path.append('/content/Person-Re-Id-Dataset')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import timm

import torch.nn.functional as F
from torch import nn
from torch.utils.data import Dataset, DataLoader

from skimage import io
from sklearn.model_selection import train_test_split

from tqdm import tqdm

"""# Configurations"""

dat_dir = '/content/Person-Re-Id-Dataset/train/'
# '/content/Person-Re-Id-Dataset/train' for dat_dir original copy
csv_file = '/content/Person-Re-Id-Dataset/train.csv'

BATCH_SIZE =32
LR = 0.001
EPOCHS =15
DEVICES = 'cuda'

df = pd.read_csv(csv_file)
df.head()

row= df.iloc[4]

a_img = io.imread(dat_dir + row.Anchor)
p_img = io.imread(dat_dir +'/'+ row.Positive)
n_img = io.imread(dat_dir + row.Negative)

f, (ax1, ax2, ax3) = plt.subplots(1,3)

ax1.set_title("Anchor")
ax1.imshow(a_img)

ax2.set_title("Positive")
ax2.imshow(p_img)

ax3.set_title("Negative")
ax3.imshow(n_img)

train, test = train_test_split(df, test_size=0.2 , random_state=42)

"""# Create APN Dataset"""

class APN_Dataset(Dataset):
  def __init__(self,df):
    self.df = df

  def __len__(self):
    return len(self.df)

  def __getitem__(self, indx) :
    row= self.df.iloc[indx]

    a_img = io.imread(dat_dir + row.Anchor)
    p_img = io.imread(dat_dir +'/'+ row.Positive)
    n_img = io.imread(dat_dir + row.Negative)

    a_img = torch.from_numpy(a_img).permute(2,0,1)/255.0
    p_img = torch.from_numpy(p_img).permute(2,0,1)/255.0
    n_img = torch.from_numpy(n_img).permute(2,0,1)/255.0

    return a_img, p_img, n_img

trainset = APN_Dataset(train)
testset = APN_Dataset(test)

indx = 40
A,P,N = trainset[indx]

f, (ax1, ax2, ax3) = plt.subplots(1,3)

ax1.set_title('Anchor')
ax1.imshow(A.numpy().transpose((1,2,0)), cmap = 'gray')

ax2.set_title('Positive')
ax2.imshow(P.numpy().transpose((1,2,0)), cmap = 'gray')

ax3.set_title('Negative')
ax3.imshow(N.numpy().transpose((1,2,0)), cmap = 'gray')

"""# Load Dataset into Batches"""

trainloader = DataLoader(trainset, batch_size=BATCH_SIZE, shuffle=True)
validloader = DataLoader(testset, batch_size=BATCH_SIZE)

print(f"No. of batches in trainloader : {len(trainloader)}")
print(f"No. of batches in validloader : {len(validloader)}")

for a,p,n in trainloader:
  print(f"Anchor shape : {a.shape}")
  print(f"Positive shape : {p.shape}")
  print(f"Negative shape : {n.shape}")
  break

"""- 32: The batch size.
- 3: The number of color channels (for RGB images).
- 128: The height of the images in pixels.
- 64: The width of the images in pixels

# Create Model
"""

class APN_Model(nn.Module):
  def __init__(self, emb_size= 512):
    super(APN_Model, self).__init__()

    self.efficient= timm.create_model('efficientnet_b0', pretrained=True)
    self.efficient.classifier = nn.Linear(in_features=self.efficient.classifier.in_features, out_features=emb_size)

  def forward(self, images):
    embeddings = self.efficient(images)
    return embeddings

model = APN_Model()
model.to(DEVICES);

"""# Create Train and Eval function"""

def train_fn(model, dataLoader, optimizer, criterion):
  model.train() #ON dropout
  total_loss = 0.0

  for a,p,n in tqdm(dataLoader):
    a,p,n = a.to(DEVICES), p.to(DEVICES), n.to(DEVICES)

    a_emb = model(a)
    p_emb = model(p)
    n_emb = model(n)

    loss = criterion(a_emb, p_emb, n_emb)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    total_loss += loss.item()

  return total_loss/len(dataLoader)

def eval_fn(model, dataloader, criterion):
  model.eval() #OFF dropout
  total_loss = 0.0

  with torch.no_grad():
    for a,p,n in tqdm(dataloader):
      a,p,n = a.to(DEVICES), p.to(DEVICES), n.to(DEVICES)
      a_emb = model(a)
      p_emb = model(p)
      n_emb = model(n)

      loss = criterion(a_emb, p_emb, n_emb)

      total_loss += loss.item()

  return total_loss/len(dataloader)

criterion = nn.TripletMarginLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LR)

"""# Create Training Loop"""

best_vaild_loss = np.inf

for i in range(EPOCHS):
  train_loss = train_fn(model, trainloader, optimizer, criterion)
  valid_loss = eval_fn(model, validloader, criterion)

  if valid_loss < best_vaild_loss:
    torch.save(model.state_dict(), 'best_model.pt')
    best_vaild_loss = valid_loss
    print("SAVED WEIGHTS SUCCESS")

  print(f"EPOCH : {i+1}")
  print(f"Train Loss : {train_loss}")
  print(f"Valid Loss : {valid_loss}")

"""# Get Anchor Embeddings"""

def get_encoding_csv(model, anc_img_names):
  anc_img_names_arr = np.array(anc_img_names)
  encodings =[]
  model.eval()
  with torch.no_grad():
    for i in tqdm(anc_img_names_arr):
      a = io.imread(dat_dir + i)
      a = torch.from_numpy(a).permute(2,0,1)/255.0
      a = a.unsqueeze(0).to(DEVICES)
      a_emb = model(a)
      encodings.append(a_emb.detach().cpu().numpy())

    encodings = np.array(encodings)
    encodings = pd.DataFrame(encodings.squeeze())
    df_emb = pd.concat([anc_img_names.reset_index(drop=True),encodings], axis=1)
    return df_emb

model.load_state_dict(torch.load('best_model.pt'))
df_enc = get_encoding_csv(model, train['Anchor'])

df_enc.to_csv('database.csv',index= False)
df_enc.head()

"""# Inference"""

def euclidean_dis(img_enc, anc_enc_arr):
  dist = np.sqrt(np.dot(img_enc - anc_enc_arr , (img_enc - anc_enc_arr).T))
  return dist

idx = 0
img_name = df_enc['Anchor'].iloc[idx]
img_path = dat_dir + img_name

img = io.imread(img_path)
img = torch.from_numpy(img).permute(2,0,1)/255.0

model.eval()
with torch.no_grad():
  img = img.to(DEVICES)
  img_enc = model(img.unsqueeze(0))
  img_enc = img_enc.detach().cpu().numpy()

anc_enc_arr = df_enc.iloc[:, 1:].to_numpy()
anc_img_names = df_enc['Anchor']

distance = []

for i in range(anc_enc_arr.shape[0]):
  dist = euclidean_dis(img_enc, anc_enc_arr[i: i+1, :])
  distance = np.append(distance, dist)

closeset_idx = np.argsort(distance)

from utils import plot_closest_imgs

plot_closest_imgs(anc_img_names, dat_dir , img, img_path, closeset_idx, distance, no_of_closest = 5);

